version: '3.8'

services:
  web:
    image: ae2079/character-analyzer:latest
    container_name: character-analyzer
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
