version: '3.8'

services:
  app:
    build: .
    container_name: character-analyzer
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_OPENAI_API_KEY=${REACT_APP_OPENAI_API_KEY}
      - BUN_ENV=production
    env_file:
      - .env
